import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Style.module.css";
import Line from "@/components/Line"
// import Button from "@/components/Button";
// import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          className={styles.view}
          name="viewport"
          content="width=device-width, initial-scale=1" 
        /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.container}>
        <div className={`${styles.box} ${styles.boxOne}`}>
            <i><Image src={"/images/twitter-logo.png"} alt="twitter" width={35} height={33} priority/></i>
            <div className={styles.text} ><h1>Sign in to X</h1></div>
            <button>
              <Image
                src={"/images/google-logo.png"}
                alt="google"
                width={20}
                height={20}
              />
              <span>Sign in with Google</span>
            </button>
            <button>
              <Image
                src={"/images/apple-logo.png"}
                alt="apple"
                width={23}
                height={22}
              />
              <span>Sign in with Apple</span>
            </button>
            <div>
            <Line/>
              <div className={`${styles.box} ${styles.boxTwo}`}>
                {/* <form> */}
                <form className={styles.userName} />
              <input
                type="text"
                placeholder="Phone, email, or username"
              />
                <button className={styles.nextBtn}>Next</button>
                <button className={styles.forBtn}>Forgot password</button>
              </div>
              <p>Don't have an account?<a href="#"> Sign up</a></p>
            </div>
          </div>
        </div>
      </main>
      {/* <footer className={styles.footer}>© Zalida Khan</footer> */}
    </>
  );
}

{
  /* <Image
          className={styles.image}
          src={"/images/twitter-logo.png"}
          alt="twitter logo"
          width={50}
          height={50}
          priority
        />
        <h1 className={styles.h1}>Sign in to X</h1>
        <Button/>
        <div>
          <input
            className={styles.textfield}
            autocorrect="on"
            name="text"
            spellcheck="true"
            type="text"
          ></input>
        </div>
        <button className={styles.button}>Next</button>
        <button className={styles.button1}>Forgot password?</button> */
}

{/* <span className={styles.between} >  or</span> */}